diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'Wheel_Left_joint'
  right_wheel: 'Wheel_Right_joint'
  publish_rate: 50
  cmd_vel_timeout: 0.5
  velocity_rolling_window_size: 10
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 1.0
      min_velocity: -1.0
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 2.0
      min_velocity: -2.0
